# Configuration for Alacritty, the GPU enhanced terminal emulator

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization.
  #
  # If this property is not set, alacritty will set it to xterm-256color.
  #
  # Note that some xterm terminfo databases don't declare support for italics.
  # You can verify this by checking for the presence of `smso` and `sitm` in
  # `infocmp xterm-256color`.
  TERM: xterm-256color

window:
  # Window dimensions in character columns and lines
  # (changes require restart)
  dimensions:
    columns: 96
    lines: 40

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0

  # Adds this many blank pixels of padding around the window
  # Units are physical pixels; this is not DPI aware.
  # (change requires restart)
  padding:
    x: 2
    y: 2

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

  # Values for `decorations`:
  #- full: Borders and title bar
  #- none: Neither borders nor title bar
  decorations: full

  # When true, alacritty starts maximized.
  # startup_mode: Fullscreen

  # Window title
  title: Terminal


scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3


selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: false


# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Fira Mono
    style: Regular

  # The bold font face
  bold:
    family: Fira Mono
    style: Bold

  # The italic font face
  italic:
    family: Fira Mono
    style: Italic

  # Point size of the font
  size: 14.0

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true


# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

# # The definition of color schemes.
# schemes:
#   gruvbox_material_hard_dark: &gruvbox_material_hard_dark
#     primary:
#       background: '0x1d2021'
#       foreground: '0xd4be98'
#     normal:
#       black:   '0x32302f'
#       red:     '0xea6962'
#       green:   '0xa9b665'
#       yellow:  '0xd8a657'
#       blue:    '0x7daea3'
#       magenta: '0xd3869b'
#       cyan:    '0x89b482'
#       white:   '0xd4be98'
#     bright:
#       black:   '0x32302f'
#       red:     '0xea6962'
#       green:   '0xa9b665'
#       yellow:  '0xd8a657'
#       blue:    '0x7daea3'
#       magenta: '0xd3869b'
#       cyan:    '0x89b482'
#       white:   '0xd4be98'
#   gruvbox_material_medium_dark: &gruvbox_material_medium_dark
#     primary:
#       background: '0x282828'
#       foreground: '0xd4be98'
#     normal:
#       black:   '0x3c3836'
#       red:     '0xea6962'
#       green:   '0xa9b665'
#       yellow:  '0xd8a657'
#       blue:    '0x7daea3'
#       magenta: '0xd3869b'
#       cyan:    '0x89b482'
#       white:   '0xd4be98'
#     bright:
#       black:   '0x3c3836'
#       red:     '0xea6962'
#       green:   '0xa9b665'
#       yellow:  '0xd8a657'
#       blue:    '0x7daea3'
#       magenta: '0xd3869b'
#       cyan:    '0x89b482'
#       white:   '0xd4be98'
#   gruvbox_material_soft_dark: &gruvbox_material_soft_dark
#     primary:
#       background: '0x32302f'
#       foreground: '0xd4be98'
#     normal:
#       black:   '0x45403d'
#       red:     '0xea6962'
#       green:   '0xa9b665'
#       yellow:  '0xd8a657'
#       blue:    '0x7daea3'
#       magenta: '0xd3869b'
#       cyan:    '0x89b482'
#       white:   '0xd4be98'
#     bright:
#       black:   '0x45403d'
#       red:     '0xea6962'
#       green:   '0xa9b665'
#       yellow:  '0xd8a657'
#       blue:    '0x7daea3'
#       magenta: '0xd3869b'
#       cyan:    '0x89b482'
#       white:   '0xd4be98'
#   gruvbox_material_hard_light: &gruvbox_material_hard_light
#     primary:
#       background: '0xf9f5d7'
#       foreground: '0x654735'
#     normal:
#       black:   '0x654735'
#       red:     '0xc14a4a'
#       green:   '0x6c782e'
#       yellow:  '0xb47109'
#       blue:    '0x45707a'
#       magenta: '0x945e80'
#       cyan:    '0x4c7a5d'
#       white:   '0xf2e5bc'
#     bright:
#       black:   '0x654735'
#       red:     '0xc14a4a'
#       green:   '0x6c782e'
#       yellow:  '0xb47109'
#       blue:    '0x45707a'
#       magenta: '0x945e80'
#       cyan:    '0x4c7a5d'
#       white:   '0xf2e5bc'
#   gruvbox_material_medium_light: &gruvbox_material_medium_light
#     primary:
#       background: '0xfbf1c7'
#       foreground: '0x654735'
#     normal:
#       black:   '0x654735'
#       red:     '0xc14a4a'
#       green:   '0x6c782e'
#       yellow:  '0xb47109'
#       blue:    '0x45707a'
#       magenta: '0x945e80'
#       cyan:    '0x4c7a5d'
#       white:   '0xeee0b7'
#     bright:
#       black:   '0x654735'
#       red:     '0xc14a4a'
#       green:   '0x6c782e'
#       yellow:  '0xb47109'
#       blue:    '0x45707a'
#       magenta: '0x945e80'
#       cyan:    '0x4c7a5d'
#       white:   '0xeee0b7'
#   gruvbox_material_soft_light: &gruvbox_material_soft_light
#     primary:
#       background: '0xf2e5bc'
#       foreground: '0x654735'
#     normal:
#       black:   '0x654735'
#       red:     '0xc14a4a'
#       green:   '0x6c782e'
#       yellow:  '0xb47109'
#       blue:    '0x45707a'
#       magenta: '0x945e80'
#       cyan:    '0x4c7a5d'
#       white:   '0xe6d5ae'
#     bright:
#       black:   '0x654735'
#       red:     '0xc14a4a'
#       green:   '0x6c782e'
#       yellow:  '0xb47109'
#       blue:    '0x45707a'
#       magenta: '0x945e80'
#       cyan:    '0x4c7a5d'
#       white:   '0xe6d5ae'

# # Apply the color scheme.
# colors: *gruvbox_material_hard_dark

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x1d2021'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'

# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 1.0

key_bindings:
  - { key: N,       mods: Control|Shift,         action: SpawnNewInstance       }
  - { key: Equals,  mods: Control,               action: IncreaseFontSize       }
  - { key: Key0,    mods: Control,               action: DecreaseFontSize       }
  - { key: F11,                                  action: ToggleFullscreen       }
