# https://beta.ruff.rs/docs/settings
line-length = 100
exclude = [".venv"]
<<<<<<< Updated upstream
ignore = ["PLR2004"]
||||||| constructed merge base
=======
ignore = ["F405"]
>>>>>>> Stashed changes
select = ["PL", "I", "F"]
